[package]
name = "eisen-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
crc = "^3.3"
uefi = "0.35.0"
uuid = { version = "1.17.0", features = ["v8"], default-features = false }

[lib]
test = false
bench = false
