[package]
name = "eisen-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
crc = "^3.3"
uefi = { version = "^0.34", features = ["alloc"] }
uefi-raw = "^0.10"
uuid = { version = "1.17.0", default-features = false }

[lib]
test = false
bench = false

[features]
alloc = []
